#99 - Criação do GoF Observer
UnBArqDsw2021-2/2021.2_G1_chapa_quente pull request #100
Opened 2022-02-25 13:41 UTC by guilhermedfs

issue:closes #99 
---

## Descrição

Foi criado o documento relacionado ao GoF Observer, assim como como a realização de uma análise crítica acerca da sua aplicação. 

## Definição de Pronto

- [ ] Adição do documento à sidebar
- [ ] Review do documento

2022-02-28 22:10 UTC, JPedroCh requested changes
Falta adicionar à sidebar e os revisores, mas bom trabalho :+1:

2022-03-01 01:03 UTC, nYCSTs requested changes
Além das mudanças apontadas pelo @JPedroCh não vi nenhum problema.

2022-03-03 12:57 UTC, PedroLimass approved these changes

2022-03-13 21:28 UTC, JPedroCh approved these changes
LGTM!

2022-03-13 21:28 UTC, nYCSTs approved these changes
LGTM

2022-03-13 21:28 UTC, merged