Criaçao do documento acerca do GOF comportamental Visitor
UnBArqDsw2021-2/2021.2_G1_chapa_quente pull request #108
Opened 2022-02-25 20:48 UTC by RodrigoTCLima

Co-authored-by: Murilo Gomes <murilo.goomes@hotmail.com>

issue:closes #105 
---

## Descrição

O documento GOF comportamental Visitor foi criado a fim de explicar seu funcionamento.

## Tarefas

- [x] Criação do documento
- [x] Adição à sidebar
- [ ] Revisão do documento

2022-03-01 00:57 UTC, nYCSTs requested changes
Realizar ajustes

2022-03-01 00:57 UTC, nYCSTs commented on docs/pages/fase_03/gof_visitor.md
> +| 1.0    | 25/02/2022 | Criação do Documento | Murilo Gomes e Rodrigo Lima |         |
Adicionar revisores

2022-03-01 00:57 UTC, nYCSTs commented on docs/pages/fase_03/gof_visitor.md
> +Analisando as caractirísticas do Visitor, percebo que, a pricipio, não é um padrão que se encaixe no projeto Chapa Quente.
trocar caractirísticas para **características**
trocar pricipio para **princípio**

2022-03-04 09:40 UTC, DafneM requested changes

2022-03-04 09:40 UTC, DafneM commented on docs/pages/fase_03/gof_visitor.md
> +Analisando as caractirísticas do Visitor, percebo que, a pricipio, não é um padrão que se encaixe no projeto Chapa Quente.
Adicionar motivo da não utilização no projeto. Exemplo: pois a linguagem utilizada não suporta, ou pois o padrão exige um tipo de classe que não existe no nosso projeto etc.

2022-03-04 09:40 UTC, DafneM commented on docs/pages/fase_03/gof_visitor.md
> +* SOURCE MAKING - Visitor Design Pattern. Disponível em: https://sourcemaking.com/design_patterns/visitor . Acesso em: 25 de fevereiro de 2022.
Adicionar pontos de vista de outros autores no documento a partir de mais alguma/algumas bibliografias.

2022-03-04 09:40 UTC, DafneM commented on docs/pages/fase_03/gof_visitor.md
> +| 1.0    | 25/02/2022 | Criação do Documento | Murilo Gomes e Rodrigo Lima |         |
Faço das suas, as minhas palavras haha

2022-03-13 22:04 UTC, nYCSTs approved these changes
LGTM

2022-03-14 00:23 UTC, DafneM approved these changes
Ok

2022-03-14 00:23 UTC, merged