Criaçao do documento acerca do GOF comportamental State
UnBArqDsw2021-2/2021.2_G1_chapa_quente pull request #109
Opened 2022-02-25 20:59 UTC by RodrigoTCLima

Co-authored-by: Murilo Gomes <murilo.goomes@hotmail.com>

issue:closes #104 
---

## Descrição

Foi criado o documento GOF comportamental State a fim de explicar seu funcionamento e possivel sua aplicação no projeto.

## Definição de Pronto

- [X] Criação do documento
- [X] Adição à sidebar
- [ ] Revisão do documento
## Descrição

2022-02-28 22:14 UTC, JPedroCh requested changes

2022-02-28 22:14 UTC, JPedroCh commented on docs/pages/fase_03/gof_state.md
> +| 1.0    | 25/02/2022 | Criação do Documento | Murilo Gomes e Rodrigo Lima |         |
Falta adicionar os revisores, porém bom trabalho :+1:

2022-03-04 09:44 UTC, DafneM requested changes
Ficou ótimo! Apenas algumas mudanças

2022-03-04 09:44 UTC, DafneM commented on docs/pages/fase_03/gof_state.md
> +| 1.0    | 25/02/2022 | Criação do Documento | Murilo Gomes e Rodrigo Lima |         |
Adicionar revisores.

2022-03-04 09:44 UTC, DafneM commented on docs/pages/fase_03/gof_state.md
> +* SOURCE MAKING - State Design Pattern. Disponível em: https://sourcemaking.com/design_patterns/state . Acesso em: 25 de fevereiro de 2022.
Colocar outro/outros pontos de vista no documento.

2022-03-13 22:07 UTC, JPedroCh approved these changes
LGTM!

2022-03-13 22:10 UTC, nYCSTs approved these changes
LGTM

2022-03-14 00:34 UTC, DafneM approved these changes
Bom trabalho!

2022-03-14 00:35 UTC, merged