Adicionado documento Template Method
UnBArqDsw2021-2/2021.2_G1_chapa_quente pull request #121
Opened 2022-02-28 03:06 UTC by Giuulob89

issue:closes 120#
---

## Descrição

Adicionado documento Template Method.

## Definição de Pronto

- [ ] Documento GOF Pronto
- [ ] Documento GOF revisado

2022-03-02 21:57 UTC, Giuulob89 commented
Pendente atualização de revisores no doc

2022-03-03 12:53 UTC, PedroLimass requested changes
Está ótimo! Só falta colocar o arquivo na sidebar.

2022-03-15 04:04 UTC, Giuulob89 commented
@PedroLimass favor revisar novamente

2022-03-15 13:03 UTC, RodrigoTCLima approved these changes

2022-03-15 21:50 UTC, PedroLimass approved these changes

2022-03-15 21:51 UTC, merged