# 114 GOF estrutural Composite
UnBArqDsw2021-2/2021.2_G1_chapa_quente pull request #123
Opened 2022-03-01 01:25 UTC by murilogds

issue:closes #114
---

## Descrição

Foi adicionado o documento sobre o GOF Estrutural Composite

## Definição de Pronto

- [x] Introdução
- [x] Metodologia
- [x] Conclusão

2022-03-04 09:50 UTC, DafneM requested changes
Ótimo trabalho! Ficou muito bom

2022-03-04 09:50 UTC, DafneM commented on docs/pages/fase_03/composite.md
> +| 1.0    | 25/02/2022 |              Criação do Documento              | Murilo Gomes e Rodrigo Lima | |
Adicionar revisores

2022-03-04 09:50 UTC, DafneM commented on docs/pages/fase_03/composite.md
> +<figcaption><a href="../../assets/images/composite.png">Figura 1:</a> Diagrama do Padrão Composite. Fonte: https://itnext.io/easy-patterns-composite-8b28aa1f158 </figcaption>
Link para a fonte está quebrando

2022-03-13 22:52 UTC, nYCSTs approved these changes
LGTM

2022-03-14 01:25 UTC, DafneM approved these changes
Show

2022-03-14 01:25 UTC, merged