Adicionado GOF Object Pool
UnBArqDsw2021-2/2021.2_G1_chapa_quente pull request #128
Opened 2022-03-02 21:16 UTC by nYCSTs

Co-authored-by: Liverson <liverson.p@gmail.com>

issue:closes #126 
---

## Descrição

Deve-se criar o documento GOF criacional **Object Pool** a fim de explicar seu funcionamento e sua aplicação no projeto.

## Tarefas

- [x] Criação do documento
- [x] Adição à sidebar
- [ ] Revisão do documento

2022-03-04 09:53 UTC, DafneM requested changes

2022-03-04 09:53 UTC, DafneM commented on docs/pages/fase_03/GOF-Object-Pool.md
> +O padrão criacional **Object Pool** é usado quando estamos lidando com classes com um algo custo de inicialização. A ideia é colocar as classes instanciadas em uma "pool", e quando for necessário ela
Trocar algo por alto

2022-03-04 09:53 UTC, DafneM commented on docs/pages/fase_03/GOF-Object-Pool.md
> +O Object Pool funciona como um local que reune as instâncias das classes, e quando necessário, e feito uma chamada pela instancia desejada. É desejado que todos os objetos instanciados estejam na mes
Trocar reune por reúne. Trocar "e feito uma chamada" por "é feita uma chamada pela"

2022-03-04 09:53 UTC, DafneM commented on docs/pages/fase_03/GOF-Object-Pool.md
> +A equipe não viu, até o momento, nenhum cenário de utilização do padrão Object Pool no projeto.
Essa parte acredito que pode ir na conclusão.

2022-03-14 01:55 UTC, DafneM approved these changes
Massa!

2022-03-14 01:56 UTC, JPedroCh approved these changes
Muito bom!

2022-03-14 01:56 UTC, merged