#132 criacional abstract factory
UnBArqDsw2021-2/2021.2_G1_chapa_quente pull request #144
Opened 2022-03-04 23:48 UTC by liversonp

Co-authored-by: Giuulob89 <giulialobo89@gmail.com>

issue:closes #
---

## Descrição

Foi elaborado o GOF abstract factory

## Definição de Pronto

- [ ] Criar o GOF abstract factory
- [ ] Adicionar o sidebar
- [ ] Revisar

2022-03-13 23:41 UTC, nYCSTs approved these changes
LGTM

2022-03-14 11:24 UTC, DafneM requested changes

2022-03-14 11:24 UTC, DafneM commented on docs/pages/fase_03/GOF_criacional_abstract_factory.md
> +</br> Figura 1 - Ilustração de Abstract Factory. Fonte: [https://thispersondoesnotexist.com/](ThisPersonDoesNotExist)
Falta adicionar a fonte da imagem! Não achei, mas deixei meio pronto. Só jogar o link aí

2022-03-15 21:48 UTC, DafneM approved these changes

2022-03-15 21:48 UTC, merged