#146 Criação do documento GoF Mediator
UnBArqDsw2021-2/2021.2_G1_chapa_quente pull request #147
Opened 2022-03-07 14:20 UTC by guilhermedfs

issue:closes #146 
---

## Descrição

Criação do documento do GoF Comportamental Mediator.
## Definição de Pronto

- [ ] Criação do documento
- [ ] Revisão do documento
- [ ] Adição à sidebar

2022-03-13 23:59 UTC, nYCSTs approved these changes
LGTM

2022-03-14 11:30 UTC, DafneM requested changes

2022-03-14 11:30 UTC, DafneM commented on docs/pages/fase_03/gofMediator.md
> + ![Mediator Exemplo](./../../assets/images/gof-mediator.png)
Não encontrei a fonte da imagem

2022-03-15 21:56 UTC, DafneM approved these changes

2022-03-15 21:56 UTC, merged