Diagrama de Estados
UnBArqDsw2021-2/2021.2_G1_chapa_quente pull request #70
Opened 2022-02-16 01:52 UTC by murilogds

**Issue:** closes #69 

## Descrição
Foi produzido o documento de Diagrama de Estados

## Tarefas
* Documentar os diagramas

2022-02-17 01:35 UTC, philipeserafim requested changes

2022-02-17 01:35 UTC, philipeserafim commented on docs/pages/fase_02/diagrama_de_estados.md
> +| 1.0    | 15/02/2022 | Criação do Documento | Murilo Gomes e Liverson Paulo | |
Adicionar revisores

2022-02-17 01:35 UTC, philipeserafim commented on docs/pages/fase_02/diagrama_de_estados.md
> +
Adicionar legenda das imagens.

Acredito que um figcaption com link para imagem seja suficiente:
```<figcaption><a href="">Figura X</a>: Diagrama xxxx. Autores: xxxxx xxxxx</figcaption>```

2022-02-17 01:35 UTC, philipeserafim commented on docs/pages/fase_02/diagrama_de_estados.md
> +https://www.dca.fee.unicamp.br/~gudwin/ftp/ea976/AtEst.pdf
Adicionar autor e título do documento e por ser um link, precisa adicionar a data de acesso.

2022-02-17 01:35 UTC, philipeserafim commented on docs/pages/fase_02/diagrama_de_estados.md
> +
Adicionar a bibliografia da disciplina

2022-02-18 01:32 UTC, nYCSTs reviewed
Fazer alterações solicitadas e resolver conflito

2022-02-18 01:32 UTC, nYCSTs commented on docs/pages/fase_02/diagrama_de_estados.md
> +| 1.0    | 15/02/2022 | Criação do Documento | Murilo Gomes e Liverson Paulo | Philipe Serafim e Giulia Lobo |
Atualizar revisores

2022-02-18 01:32 UTC, nYCSTs commented on docs/pages/fase_02/diagrama_de_estados.md
> +É um diagrama do tipo dinâmico, esse diagrama também é conhecido como diagrama de máquina de estados. Esse tipo de diagrama é utilizado para modelar um comportamento discreto em sistemas de transição
Mudar "É um diagrama do tipo dinâmico, esse diagrama também é conhecido como diagrama de máquina de estados" para "É um diagrama do tipo dinâmico, também sendo conhecido como diagrama de máquina de estados" para evitar repetição de palavras

2022-02-18 02:09 UTC, nYCSTs approved these changes

2022-02-18 02:25 UTC, philipeserafim commented on docs/pages/fase_02/diagrama_de_estados.md
> +| 1.0    | 15/02/2022 | Criação do Documento | Murilo Gomes e Liverson Paulo | Philipe Serafim e Giulia Lobo |
Atualizado

2022-02-18 02:25 UTC, philipeserafim commented on docs/pages/fase_02/diagrama_de_estados.md
> +É um diagrama do tipo dinâmico, esse diagrama também é conhecido como diagrama de máquina de estados. Esse tipo de diagrama é utilizado para modelar um comportamento discreto em sistemas de transição
Resolvido

2022-02-18 02:26 UTC, philipeserafim approved these changes

2022-02-18 02:45 UTC, Giuulob89 approved these changes
Aprovado!

2022-02-18 13:08 UTC, PedroLimass approved these changes

2022-02-18 13:08 UTC, merged