Adicionada documentacao agil
UnBArqDsw2021-2/2021.2_G1_chapa_quente pull request #76
Opened 2022-02-17 00:32 UTC by DafneM

**Issue:** closes #60 

## Descrição
Foi criada toda a modelagem ágil, épicos, features, histórias de usuário e backlog

## Tarefas
* Épicos
* Features
* HIstórias de usuário
* Backlog

2022-02-17 02:15 UTC, murilogds requested changes

2022-02-17 02:15 UTC, murilogds commented on docs/_sidebar.md
> +    - [Backlog do produto](pages/fase_02/modelagem_agil/backlog_produto.md)
Aqui do jeito que ficou as apresentações do tópico passado ficaram no tópico de Modelagem, o certo seria fazer um merge da main nessa branch aqui pra evitar conflito e deixar certinho

2022-02-17 02:15 UTC, murilogds commented on docs/pages/fase_02/modelagem_agil/historias_usuario.md
> +F01
Esses Fs ficaram meio estranhos, acho que o melhor seria tirar eles, vou apontar todos

2022-02-17 02:15 UTC, murilogds commented on docs/pages/fase_02/modelagem_agil/historias_usuario.md
> +F02
Aqui

2022-02-17 02:15 UTC, murilogds commented on docs/pages/fase_02/modelagem_agil/historias_usuario.md
> +F03
Aqui

2022-02-17 02:15 UTC, murilogds commented on docs/pages/fase_02/modelagem_agil/historias_usuario.md
> +F04
Aqui

2022-02-17 02:15 UTC, murilogds commented on docs/pages/fase_02/modelagem_agil/historias_usuario.md
> +F05
Aqui é o último pelo que eu vi

2022-02-17 02:15 UTC, murilogds commented on docs/pages/fase_02/modelagem_agil/backlog_produto.md
> +| 1.0    | 15/02/2022 | Criação do Documento |  Dafne Moretti Moreira |       |
Adicionar revisor

2022-02-17 02:15 UTC, murilogds commented on docs/pages/fase_02/modelagem_agil/epicos.md
> +| 1.0    | 15/02/2022 | Criação do Documento |  Dafne Moretti Moreira |       |
Adicionar revisor

2022-02-17 02:15 UTC, murilogds commented on docs/pages/fase_02/modelagem_agil/historias_usuario.md
> +| 1.0    | 15/02/2022 | Criação do Documento |  Dafne Moretti Moreira |       |
Adicionar revisor

2022-02-18 01:57 UTC, murilogds requested changes
Resolver conflitos e fazer essas alterações

2022-02-18 01:57 UTC, murilogds commented on docs/pages/fase_02/modelagem_agil/backlog_produto.md
> +| 1.0    | 15/02/2022 | Criação do Documento |  Dafne Moretti Moreira |  	Murilo Gomes de Souza e     |
Atualizar os revisores

2022-02-18 01:57 UTC, murilogds commented on docs/pages/fase_02/modelagem_agil/backlog_produto.md
> +Para a construção do Backlog do Produto, dois integrantes do time fizeram um [backlog individual 1](../pages/fase_02/modelagem_agil/backlog_produto?id=backlog-individual-1) e o [backlog individual 2]
Acho que aqui podia especificar qual integrante fez qual backlog que aí melhora a rastreabilidade

2022-02-18 02:29 UTC, guilhermedfs approved these changes

2022-02-18 02:58 UTC, JPedroCh approved these changes
Bom trabalho!

2022-02-18 11:59 UTC, murilogds approved these changes

2022-02-18 13:20 UTC, PedroLimass approved these changes

2022-02-18 13:22 UTC, merged