Documento de Estimativa - Iniciativa Extra
UnBArqDsw2021-2/2021.2_G1_chapa_quente pull request #77
Opened 2022-02-17 01:09 UTC by PedroLimass

Issue: closes #67

2022-02-17 03:53 UTC, Giuulob89 commented on docs/pages/fase_02/iniciativasExtras/estimativas.md
> +    *E que essas possuem coeficientes, representados pela tabela a seguir:*
Fazer uma correção nessa linha. Essa frase deve ser em itálico e deve estar alinhada com o texto em itálico mais acima

2022-02-17 03:53 UTC, Giuulob89 commented on docs/pages/fase_02/iniciativasExtras/estimativas.md
> +*Custo = T(horas[considerando um dia com 8hs]) x custo-aluno x quantidade-alunos*
Na fórmula vamos colocar apenas Custo = T(horas) X custo-aluno X E (que é o esforço, logo, a quantidade de alunos) e na descrição abaixo explicamos que serão consideradas 8hs por dia

2022-02-17 03:53 UTC, Giuulob89 commented on docs/pages/fase_02/iniciativasExtras/estimativas.md
> +* **T (horas)** = 9;
Nessa linha colocamos T (horas) = valor (considerando 8hs trabalhadas por dia)
Sendo que o valor que eu calculei para o T (horas) foi 240hs mensais X 5 meses, dando 1200 horas, então o valor desse 9 pode ser substituído por 1200

2022-02-17 03:53 UTC, Giuulob89 commented on docs/pages/fase_02/iniciativasExtras/estimativas.md
> +* **c** = 2,50;
Aqui, invés de ser c, vamos colocar custo-aluno e no valor, devemos colocar 2,04, que é o custo por cada aluno. Importante também especificar que o valor do custo-aluno foi definido a partir de uma das referências, que é o relatório geral de custos da UnB. Tentar linká-lo nessa parte.

2022-02-17 03:53 UTC, Giuulob89 commented on docs/pages/fase_02/iniciativasExtras/estimativas.md
> +* **d** = 0,35.
Aqui também não será d, iremos substituir pelo E, de esforço, ou seja, quantidade de alunos e o valor é 9

2022-02-17 03:53 UTC, Giuulob89 commented on docs/pages/fase_02/iniciativasExtras/estimativas.md
> +*Custo = 2,50 x 9^0,35*
A fórmula então, fica construída assim:
Custo = 1200 x 2,04 x 9

2022-02-17 03:53 UTC, Giuulob89 commented on docs/pages/fase_02/iniciativasExtras/estimativas.md
> +*Custo = R$ 7280,00*
Logo, o resultado é Custo = R$ 22.032,00

2022-02-17 03:53 UTC, Giuulob89 commented on docs/pages/fase_02/iniciativasExtras/estimativas.md
> +| Mão de obra | 7.280,00 |
Ao substituir o valor aqui, aí sim teremos o valor total (apesar de não acreditar que seja tão relevante o levantamento de custos das ferramentas)

2022-02-18 01:37 UTC, murilogds approved these changes

2022-02-18 02:43 UTC, philipeserafim requested changes

2022-02-18 02:43 UTC, philipeserafim commented on docs/pages/fase_02/iniciativasExtras/estimativas.md
> +* *Posteriomente, é necessário saber que ele também pode ser aplicado em três classes de projeto, que são:*
Posteriomente -> Posteriormente

2022-02-18 02:43 UTC, philipeserafim commented on docs/pages/fase_02/iniciativasExtras/estimativas.md
> +De acordo com essa tabela e após discussão entre o grupo, podemos definir uma média total de linhas em, aproximandamente, **2128 linhas = 2128 Loc**, ou seja **2,128 KLoc**, que pode ser aproximado p
aproximandamente -> aproximadamente

2022-02-18 02:43 UTC, philipeserafim commented on docs/pages/fase_02/iniciativasExtras/estimativas.md
> +| 1.3    | 17/02/2022 | Últimas alterações na conclusão | Giulia Lobo Barros |      Philipe Serafim       |
Atualizar revisores

2022-02-18 02:49 UTC, liversonp commented
Os iframes das linhas 38 e 76 não estão funcionando como deveriam
Erro de português linha 163: "custo dão mão de obra"

2022-02-18 12:52 UTC, liversonp approved these changes

2022-02-18 16:37 UTC, DafneM approved these changes
UAU! Bom trabalho

2022-02-18 17:04 UTC, philipeserafim approved these changes

2022-02-18 17:06 UTC, merged