#51 diagrama de componentes
UnBArqDsw2021-2/2021.2_G1_chapa_quente pull request #78
Opened 2022-02-17 05:41 UTC by JPedroCh

issue:closes #51 
---

## Descrição

Adicionado o documento de diagrama de componentes.

## Definição de Pronto

- [ ] Introdução 
- [ ] Legenda 
- [ ] Metodologia 
- [ ] Bibliografia

2022-02-17 16:48 UTC, guilhermedfs requested changes
O diagrama foi muito bem construído. São necessárias somente algumas mudanças na escrita do texto e me inserir como revisor no documento.

2022-02-17 16:48 UTC, guilhermedfs commented on docs/pages/fase_02/diagrama_de_componentes.md
> +O diagrama de componentes é um diagrama estático cuja função principal é apresentar os componentes (módulos mais “gerais” do sistema) e suas relações com os demais subsistemas e componentes. A utiliz
Talvez seja interessante retirar as aspas do gerais, deixa o texto muito informal.

2022-02-17 16:48 UTC, guilhermedfs commented on docs/pages/fase_02/diagrama_de_componentes.md
> +O desenvolvimento do diagrama de componentes foi feito com base a documentação do **Chapa Quente** e chegamos nos seguintes subsistemas: Autenticação, Lanchonete, Pedido, Cardápio. A plataforma utili
Acho que seria "com base na...". Talvez seja interessante trocar "e com os elementos..." para "e dispõe dos/apresenta os" (escolher uma dessas).

2022-02-17 17:43 UTC, JPedroCh commented on docs/pages/fase_02/diagrama_de_componentes.md
> +O desenvolvimento do diagrama de componentes foi feito com base a documentação do **Chapa Quente** e chegamos nos seguintes subsistemas: Autenticação, Lanchonete, Pedido, Cardápio. A plataforma utili
Feito!

2022-02-17 17:43 UTC, JPedroCh commented on docs/pages/fase_02/diagrama_de_componentes.md
> +O diagrama de componentes é um diagrama estático cuja função principal é apresentar os componentes (módulos mais “gerais” do sistema) e suas relações com os demais subsistemas e componentes. A utiliz
Feito!

2022-02-18 01:50 UTC, nYCSTs reviewed
Fazer alterações solicitadas

2022-02-18 01:50 UTC, nYCSTs commented on docs/pages/fase_02/diagrama_de_componentes.md
> +| 1.3 | 17/02/2022 | Correções ortográficas nos textos solicitadas pelo revisor | João Pedro Alves da Silva Chaves | Guilherme Daniel Fernandes da Silva |
Atualizar revisores

2022-02-18 01:50 UTC, nYCSTs commented on docs/pages/fase_02/diagrama_de_componentes.md
> +<figcaption>Figura 01. Imagem que contém o diagrama de componentes da aplicação.</figcaption>
Ajustar os \<figcaption> com autor e link para imagem

2022-02-18 02:11 UTC, nYCSTs approved these changes

2022-02-18 02:20 UTC, RodrigoTCLima approved these changes

2022-02-18 02:21 UTC, guilhermedfs approved these changes

2022-02-18 12:32 UTC, PedroLimass commented on docs/pages/fase_02/diagrama_de_componentes.md
> +# Nome do Artefato
Faltou adicionar  o nome do artefato. Acabou que ficou o valor padrão do template.

2022-02-18 12:33 UTC, PedroLimass commented on docs/pages/fase_02/diagrama_de_componentes.md
> +| 1.4 | 17/02/2022 | Correções nas legendas das figuras | João Pedro Alves da Silva Chaves | Guilherme Daniel Fernandes da Silva, Rodrigo Tiago Costa Lima, Lucas da Cunha Andrade e Dafne Moretti More
Me adicionar como revisor: Pedro Lima

2022-02-18 12:42 UTC, PedroLimass commented on docs/pages/fase_02/diagrama_de_componentes.md
> +| ![Interface](./../../assets/images/interface.png ":size=200") </br> Fonte: Autoria própria   | Interface |  Simboliza a interface necessária para o relacionamento entre os componentes. |
Remover "Fonte: Autoria própria" e colocar logo ao final da tabela uma única legenda no estilo que segue na `documentação: ```<figcaption style="text-align: center">Tabela Legenda dos Componentes. Autores: João Pedro</figcaption>```

Quanto a descrição da tabela fica a seu critério mas colocar o respectivos autores como esta no exemplo.

2022-02-18 12:45 UTC, PedroLimass commented on docs/pages/fase_02/diagrama_de_componentes.md
> +<figcaption><a href="../../assets/images/subsistema_pedido.png">Figura 05</a>: Subsistema Cardápio do diagrama de componentes. Autores: João Pedro Alves da Silva Chaves e Dafne Moretti Moreira</figca
Adicionar ```style="text-align: center"``` dentro da tag do *figcaption* para alinhar a legenda ao centro e seguir o padrão das legendas.

2022-02-18 12:48 UTC, PedroLimass requested changes
Tá ótimo o documento! As alterações que solicitei é mais com o intuito de seguir um padrão na documentação e detalhes que faltaram.

2022-02-18 12:55 UTC, JPedroCh commented on docs/pages/fase_02/diagrama_de_componentes.md
> +| ![Interface](./../../assets/images/interface.png ":size=200") </br> Fonte: Autoria própria   | Interface |  Simboliza a interface necessária para o relacionamento entre os componentes. |
Feito!

2022-02-18 12:55 UTC, JPedroCh commented on docs/pages/fase_02/diagrama_de_componentes.md
> +<figcaption><a href="../../assets/images/subsistema_pedido.png">Figura 05</a>: Subsistema Cardápio do diagrama de componentes. Autores: João Pedro Alves da Silva Chaves e Dafne Moretti Moreira</figca
Feito!

2022-02-18 12:55 UTC, JPedroCh commented on docs/pages/fase_02/diagrama_de_componentes.md
> +| 1.4 | 17/02/2022 | Correções nas legendas das figuras | João Pedro Alves da Silva Chaves | Guilherme Daniel Fernandes da Silva, Rodrigo Tiago Costa Lima, Lucas da Cunha Andrade e Dafne Moretti More
Feito!

2022-02-18 12:59 UTC, PedroLimass approved these changes

2022-02-18 12:59 UTC, merged