Criação do documento de Project Backlog
UnBArqDsw2021-2/2021.2_G1_chapa_quente pull request #81
Opened 2022-02-17 14:03 UTC by nYCSTs

issue:closes #52 
---

## Descrição

Deve-se criar o documento de backlog do projeto a fim de facilitar a definição do escopo do projeto.

## Tarefas

- [ ] Definição dos items que farão parte do documento
- [ ] Criação do documento
- [ ] Revisão

2022-02-17 17:31 UTC, JPedroCh requested changes

2022-02-17 17:31 UTC, JPedroCh commented on docs/pages/fase_02/backlog_projeto.md
> +|        [EP01 - Conta](/pages/fase_02/modelagem_agil/epicos?id=ep01-conta) | F01 - Criação do usuário | [US01](/pages/fase_02/modelagem_agil/historias_usuario?id=us01)  </br> | MUST | [RF04](/pages/
O link para as histórias de usuário está resultando em page not found.

2022-02-18 02:26 UTC, guilhermedfs requested changes
Realizar algumas mudanças solicitadas.

2022-02-18 02:26 UTC, guilhermedfs commented on docs/pages/fase_02/backlog_projeto.md
> +O Project Backlog é uma das várias ferramentas ageis voltadas para a gestão de projetos, que consiste em uma lista de funcionalidades e que são ordenadas considerando a prioridade dessa funcionalidad
"ágeis"

2022-02-18 02:26 UTC, guilhermedfs commented on docs/pages/fase_02/backlog_projeto.md
> +Essa ferramenta se assemelha a ideia trazida pelo Product Backlog, porém aqui existe uma consideração com o tempo disponível para a elaboração do projeto. No Project Backlog, assim como no Product Ba
Tirar a vírgula antes do e em: "...projeto, e considerando...."

2022-02-18 02:26 UTC, guilhermedfs commented on docs/pages/fase_02/backlog_projeto.md
> +Para a elaboração do Backlog do Projeto, assim como no levantamento de algumas informações adicionais, foram utilizadas as seguintes tecnicas:
Adicionar acento em "tecnicas": técnicas

2022-02-18 02:26 UTC, guilhermedfs commented on docs/pages/fase_02/backlog_projeto.md
> +Para os valores de **risco** foi utilizado o risco relativo, obtidos atráves da tecnica de FTF.
Adicionar acento em "tecnicas": técnicas

2022-02-18 02:48 UTC, RodrigoTCLima reviewed
Por favor realize a atualização dos revisores

2022-02-18 02:48 UTC, RodrigoTCLima commented on docs/pages/fase_02/backlog_projeto.md
> +| 1.0    | 09/02/2022 | Criação do Documento | Lucas Andrade | João Pedro Alves da Silva Chaves |
Atualizar os revisores

2022-02-18 02:49 UTC, Giuulob89 requested changes
Apesar do grupo ter mapeado o backlog como uma iniciativa extra, acredito que este conte como um artefato obrigatório, pelo que está descrito no documento de detalhamento do projeto feito pela professora

2022-02-18 03:32 UTC, Giuulob89 approved these changes
Aprovado!

2022-02-18 11:10 UTC, JPedroCh approved these changes
Bom trabalho!

2022-02-18 14:20 UTC, guilhermedfs approved these changes
👍🏻

2022-02-18 15:12 UTC, RodrigoTCLima approved these changes

2022-02-18 15:16 UTC, merged