#97 - GoF Singleton criado e documentado
UnBArqDsw2021-2/2021.2_G1_chapa_quente pull request #98
Opened 2022-02-25 12:46 UTC by guilhermedfs

issue:closes #97 

## Descrição

GoF do padrão Singleton foi criado e devidamente documentado.

## Definição de Pronto

- [ ] Adição do documento à Sidebar
- [ ] Revisão do documento aprovada

2022-03-02 16:11 UTC, Giuulob89 requested changes
Colocar revisores no documento

2022-03-10 20:05 UTC, JPedroCh approved these changes
Bom trabalho!

2022-03-10 20:09 UTC, nYCSTs approved these changes

2022-03-16 13:09 UTC, Giuulob89 requested changes

2022-03-16 13:09 UTC, Giuulob89 commented on docs/pages/fase_03/gofSingleton.md
> +O padrão Singleton é amplamente utilizado na indústria e soluciona problemas recorrentes em diversas aplicações. Todavia, deve ser utilizado com cautela para que não se torne um antipadrão devido, pr
Acredito que faltou apenas deixar mais claro se o grupo vai usar esse padrão ou não

2022-03-16 15:57 UTC, Giuulob89 requested changes

2022-03-16 15:57 UTC, Giuulob89 commented on docs/pages/fase_03/gofSingleton.md
> +O padrão Singleton é amplamente utilizado na indústria e soluciona problemas recorrentes em diversas aplicações. Todavia, deve ser utilizado com cautela para que não se torne um antipadrão devido, pr
Acredito que ainda falta trazer a decisão do grupo quanto ao uso desse padrão

2022-03-16 21:16 UTC, Giuulob89 approved these changes
Aprovado!

2022-03-16 21:16 UTC, merged